name: Frosty-Anime-Server
on:
  workflow_dispatch:
  schedule:
   - cron:  '0 6 * * *'
      
jobs:
  run-sync-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Downloading Files 
        run: |
           ls
      - name: Installing Requirements
        run: |
           sudo pip install -r requirements.txt
      - name: Running Script
        run: |
             python3 AniDl.py
